name: Kupool
description: "KuPool"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  flutter_screenutil: ^5.9.3
  dio: ^5.9.0
  pinput: ^4.0.0
  fluttertoast: ^8.2.6
  flutter_riverpod: ^3.1.0
  fl_chart: ^0.68.0
  shimmer: ^3.0.0
  liquid_pull_to_refresh: ^3.0.1
  shared_preferences: ^2.2.3
  cupertino_icons: ^1.0.8
  flutter_smart_dialog: ^4.9.7+2
  provider: ^6.1.5+1
  intl: ^0.20.2
  easy_refresh: ^3.4.0
  flutter_inappwebview: ^6.1.5
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - images/earn/
    - images/home/
    - images/machine/
    - images/mine/
    - images/panel/
    - images/login/